# Generated by Django 4.2.6 on 2023-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Comments",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Followers",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Followings",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Handle_Name",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Image_Type",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Impressions",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Likes",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Name",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Post_Url",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Project_Executive",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Retweet",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Video_Type",
            field=models.CharField(default="", max_length=200),
        ),
    ]
