# Generated by Django 4.2.6 on 2023-10-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appname", "0002_alter_googlesheetdata_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Followers",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="googlesheetdata",
            name="Followings",
            field=models.IntegerField(default="0"),
        ),
    ]
